version: "3.8"

services:
  browserless:
    image: browserless/chrome:latest
    security_opt:
      - seccomp:unconfined
    environment:
      - CONCURRENT:10
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
