module.exports = {
    headless: false,
    ignoreDefaultArgs: false,
    devtools: false,
    defaultViewport: {
        width: 400,
        height: 400
    },
    args: [
        '--hide-scrollbars',
        '--mute-audio',
        '--disable-canvas-aa', // Disable antialiasing on 2d canvas
        '--disable-2d-canvas-clip-aa', // Disable antialiasing on 2d canvas clips
        '--disable-gl-drawing-for-tests', // BEST OPTION EVER! Disables GL drawing operations which produce pixel output. With this the GL output will not be correct but tests will run faster.
        '--disable-dev-shm-usage', // ???
        '--no-zygote', // wtf does that mean ?
        '--use-gl=desktop', // better cpu usage with --use-gl=desktop rather than --use-gl=swiftshader, still needs more testing.
        '--enable-webgl',
        '--no-first-run',
        '--disable-infobars',
        '--disable-breakpad',
        '--incognito',
        '--window-size=400,400',
        '--disable-gpu',
        '--disable-font-subpixel-positioning',
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--no-zygote',
        '--disable-crash-reporter',
        '--crashpad-handler-pid=0',
        '--disable-blink-features=AutomationControlled',
        '--disable-accelerated-2d-canvas',
        '--disable-3d-apis',
        '--disable-background-media-suspend',
        '--disable-background-timer-throttling',
        '--disable-backing-store-limit',
        '--disable-in-process-stack-traces',
        '--disable-input-event-activation-protection',
        '--disable-logging',
        '--disable-notifications',
        '--disable-print-preview',
        '--disable-rgba-4444-textures',
        '--disable-pinch',
        '--disable-partial-raster',
        '--disable-partitioned-cookies',
        '--disable-features',
        '--disable-extensions',
        '--disable-databases',
        '--disable-chrome-tracing-computation',
        '--disable-cancel-all-touches',
        '--disable-checker-imaging',
        '--disable-audio-input',
        '--disable-audio-output',
        '--disable-angle-features',
        '--disable-app-content-verification',
        '--disable-adpf',
        '--disable-auto-reload',
        '--disable-auto-maximize-for-tests',
        '--disable-best-effort-tasks',
        '--disable-default-apps',
        '--disable-extensions-file-access-check',
        '--disable-extensions-http-throttling',
        '--disable-domain-blocking-for-3d-apis',
        '--disable-rollback-option',
        '--disable-smooth-scrolling',
        '--disable-speech-api',
        '--disable-speech-synthesis-api',
        '--disable-stack-profiler',
        '--disable-threaded-animation',
        '--disable-touch-drag-drop',
        '--disable-virtual-keyboard',
        '--no-default-browser-check',
        '--disable-birch-weather-api-for-testing',
        '--disable-android-native-fence-sync-for-testing',
        '--disable-checking-optimization-guide-user-permissions',
        '--arc-disable-download-provider',
        '--arc-disable-gms-core-cache',
        '--arc-disable-locale-sync',
        '--arc-disable-media-store-maintenance',
        '--arc-disable-play-auto-install',
        '--arc-disable-tts-cache',
        '--ash-disable-touch-exploration-mode',
        '--ash-hide-notifications-for-factory',
        '--disable-overscroll-edge-effect',
        '--disable-pdf-tagging',
        '--disable-pepper-3d',
        '--disable-wayland-ime',
    ]
}